/**
 * ============================================================================
 * PRODUCT DATA MODEL (Product.js)
 * ============================================================================
 * Purpose:
 *   Defines the MongoDB schema and Mongoose model for products in the 1Fi
 *   Marketplace. It models complex ecommerce and fintech entities including
 *   multi-variant attributes (color, storage), dynamic pricing (MRP vs Selling Price),
 *   and fintech-specific EMI financing options (tenures, interest rates, No-Cost EMI flags).
 *
 * Why Embedded Subdocuments for Variants and EMI Plans?
 *   1. Atomic Consistency: Products, their variants, and eligible EMI plans are
 *      retrieved in a single query without complex SQL-style joins or `$lookup`.
 * Key Schema Features:
 *   - Embedded variants and EMI financing plans for atomic reads.
 *   - Stored base price field for indexed sort and range filtering.
 *   - Dynamic virtual getters for starting EMI and discount percentage.
 *   - Compound text indexing for fast multi-field full-text search.
 * ============================================================================
 */

// Import Mongoose library to create schemas, validation rules, and model instances
import mongoose from 'mongoose';

/**
 * ImageSchema (Subdocument):
 * Represents a single product image hosted on Cloudinary CDN.
 */
const ImageSchema = new mongoose.Schema(
  {
    // Secure HTTPS URL generated by Cloudinary for high-speed CDN delivery
    url: {
      type: String,
      required: [true, 'Image URL is required'],
      trim: true,
    },
    // Unique identifier in Cloudinary used for programmatic deletion or transformations
    publicId: {
      type: String,
      required: [true, 'Cloudinary public ID is required'],
      trim: true,
    },
    // Accessibility alt text for screen readers and SEO optimization
    alt: {
      type: String,
      default: 'Product image',
      trim: true,
    },
    // Flag indicating whether this is the primary hero image for catalog cards
    isPrimary: {
      type: Boolean,
      default: false,
    },
  },
  // Disable automatic _id generation for lightweight image subdocuments
  { _id: false }
);

/**
 * VariantSchema (Subdocument):
 * Represents a specific SKU configuration (e.g., "Deep Purple / 256GB").
 * Each variant has its own independent price, MRP, stock count, and images.
 */
const VariantSchema = new mongoose.Schema({
  // Human-readable variant title (e.g. "Titanium Black - 256GB")
  name: {
    type: String,
    required: [true, 'Variant name is required'],
    trim: true,
  },
  // Stock Keeping Unit - unique business identifier for inventory tracking
  sku: {
    type: String,
    required: [true, 'SKU is required'],
    trim: true,
    uppercase: true,
  },
  // Discounted selling price in INR (Indian Rupee)
  price: {
    type: Number,
    required: [true, 'Variant selling price is required'],
    min: [0, 'Price cannot be negative'],
  },
  // Maximum Retail Price (original printed price) in INR for discount calculations
  mrp: {
    type: Number,
    required: [true, 'Variant MRP is required'],
    min: [0, 'MRP cannot be negative'],
  },
  // Current available units in warehouse
  stock: {
    type: Number,
    required: [true, 'Stock count is required'],
    min: [0, 'Stock cannot be negative'],
    default: 10,
  },
  // Dynamic attribute key-value pairs (e.g., { color: "Midnight", storage: "256GB" })
  attributes: {
    type: Map,
    of: String,
    default: {},
  },
  // Array of images specific to this colorway or variant
  images: [ImageSchema],
});

/**
 * EmiPlanSchema (Subdocument):
 * Models a pre-calculated credit financing plan for fintech BNPL checkout.
 * Powers the 1Fi "No-Cost EMI" and low-interest financing features.
 */
const EmiPlanSchema = new mongoose.Schema({
  // Duration of repayment in months (e.g., 3, 6, 9, 12, 18, 24)
  tenureMonths: {
    type: Number,
    required: [true, 'Tenure in months is required'],
    enum: [3, 6, 9, 12, 18, 24],
  },
  // Annualized interest rate percentage (0% for No-Cost EMI promotions)
  interestRate: {
    type: Number,
    required: [true, 'Interest rate is required'],
    default: 0,
    min: [0, 'Interest rate cannot be negative'],
  },
  // Calculated monthly installment amount in INR
  monthlyInstallment: {
    type: Number,
    required: [true, 'Monthly installment amount is required'],
    min: [1, 'Monthly installment must be greater than 0'],
  },
  // Upfront cash payment required at the time of purchase (₹0 for zero-down promotions)
  downPayment: {
    type: Number,
    default: 0,
    min: [0, 'Down payment cannot be negative'],
  },
  // One-time bank / NBFC processing fee in INR
  processingFee: {
    type: Number,
    default: 0,
    min: [0, 'Processing fee cannot be negative'],
  },
  // Highlight flag: True if the brand/merchant subsidizes all interest (No-Cost EMI)
  isNoCost: {
    type: Boolean,
    default: false,
  },
  // Special cashback incentive credited after loan activation
  cashbackAmount: {
    type: Number,
    default: 0,
  },
  // Minimum basket amount required to unlock this EMI tier
  minTransactionAmount: {
    type: Number,
    default: 0,
  },
});

/**
 * ProductSchema:
 * Primary schema representing the ecommerce product entity.
 */
const ProductSchema = new mongoose.Schema(
  {
    // Full marketing title of the product
    title: {
      type: String,
      required: [true, 'Product title is required'],
      trim: true,
      maxlength: [160, 'Title cannot exceed 160 characters'],
    },
    // URL-friendly unique identifier (e.g., "apple-iphone-15-pro-max")
    slug: {
      type: String,
      required: [true, 'Slug is required'],
      unique: true,
      trim: true,
      lowercase: true,
      index: true,
    },
    // Brand name (e.g. "Apple", "Samsung", "Sony")
    brand: {
      type: String,
      required: [true, 'Brand is required'],
      trim: true,
      index: true,
    },
    // Category classification (e.g., "Smartphones", "Laptops", "Audio", "Wearables")
    category: {
      type: String,
      required: [true, 'Category is required'],
      trim: true,
      index: true,
    },
    // Short marketing tagline for product cards
    tagline: {
      type: String,
      trim: true,
      default: '',
    },
    // Detailed HTML/Markdown rich description for the product detail view
    description: {
      type: String,
      required: [true, 'Product description is required'],
      trim: true,
    },
    // Array of key promotional bullet points
    highlights: [
      {
        type: String,
        trim: true,
      },
    ],
    // Array of product variants (color/storage combinations)
    variants: {
      type: [VariantSchema],
      validate: [
        (val) => val.length > 0,
        'Product must contain at least one variant',
      ],
    },
    // Array of eligible EMI financing options
    emiPlans: {
      type: [EmiPlanSchema],
      default: [],
    },
    // Average customer satisfaction rating (out of 5.0)
    rating: {
      type: Number,
      default: 4.5,
      min: [1, 'Rating must be at least 1.0'],
      max: [5, 'Rating cannot exceed 5.0'],
    },
    // Total count of verified customer reviews
    reviewCount: {
      type: Number,
      default: 0,
      min: [0, 'Review count cannot be negative'],
    },
    // Promoted placement flag on marketplace feed
    isFeatured: {
      type: Boolean,
      default: false,
      index: true,
    },
    // Promotional badge label (e.g., "Bestseller", "Top Deal", "New Launch")
    badge: {
      type: String,
      trim: true,
      default: '',
    },
    // Search tags and keywords for faceted queries
    tags: [
      {
        type: String,
        trim: true,
        lowercase: true,
      },
    ],
    // Flag to soft-delete or hide out-of-circulation items
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    // Materialized minimum variant price for indexing, sorting and range filters
    basePriceStored: {
      type: Number,
      default: 0,
      index: true,
    },
  },
  {
    // Automatically record createdAt and updatedAt timestamps
    timestamps: true,
    // Enable virtual fields when converting Mongoose documents to JSON
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/**
 * ----------------------------------------------------------------------------
 * VIRTUAL PROPERTIES
 * ----------------------------------------------------------------------------
 * Computed fields that are calculated on-the-fly and included in API responses
 * without consuming physical disk storage in MongoDB.
 */

// Virtual: startingEmi
// Determines the lowest monthly EMI installment among all available plans
ProductSchema.virtual('startingEmi').get(function () {
  // Check if emiPlans array exists and is not empty
  if (!this.emiPlans || this.emiPlans.length === 0) {
    // If no explicit plans are configured, return 0
    return 0;
  }
  // Map all monthly installments and return the minimum value
  const installments = this.emiPlans.map((plan) => plan.monthlyInstallment);
  return Math.min(...installments);
});

// Virtual: basePrice
// Gets the lowest selling price across all product variants (starting price)
ProductSchema.virtual('basePrice').get(function () {
  if (!this.variants || this.variants.length === 0) {
    return 0;
  }
  const prices = this.variants.map((variant) => variant.price);
  return Math.min(...prices);
});

// Virtual: baseMrp
// Gets the MRP corresponding to the primary base variant for discount calculation
ProductSchema.virtual('baseMrp').get(function () {
  if (!this.variants || this.variants.length === 0) {
    return 0;
  }
  const mrps = this.variants.map((variant) => variant.mrp);
  return Math.max(...mrps);
});

// Virtual: discountPercentage
// Calculates total savings percentage off the base MRP
ProductSchema.virtual('discountPercentage').get(function () {
  const price = this.basePrice;
  const mrp = this.baseMrp;
  if (mrp > 0 && price < mrp) {
    return Math.round(((mrp - price) / mrp) * 100);
  }
  return 0;
});

// Virtual: primaryImage
// Retrieves the primary image or the first available image of the first variant
ProductSchema.virtual('primaryImage').get(function () {
  if (this.variants && this.variants.length > 0) {
    const firstVariant = this.variants[0];
    if (firstVariant.images && firstVariant.images.length > 0) {
      // Find explicitly marked primary image or default to first image
      const primary = firstVariant.images.find((img) => img.isPrimary);
      return primary ? primary.url : firstVariant.images[0].url;
    }
  }
  return null;
});

/**
 * ----------------------------------------------------------------------------
 * DATABASE INDEXES
 * ----------------------------------------------------------------------------
 * Optimization indexes for fast search and filtering queries.
 */

// Compound Text Index for fast multi-field search queries (title, brand, category, tags)
ProductSchema.index({
  title: 'text',
  brand: 'text',
  category: 'text',
  tags: 'text',
});

// Indexes for category filtering combined with price and date sorting
ProductSchema.index({ category: 1, createdAt: -1 });
ProductSchema.index({ category: 1, basePriceStored: 1 });
ProductSchema.index({ isFeatured: 1, rating: -1 });

/**
 * Pre-save middleware hook:
 * Automatically computes and synchronizes basePriceStored from the lowest variant price.
 */
ProductSchema.pre('save', function (next) {
  if (this.variants && this.variants.length > 0) {
    const prices = this.variants.map((v) => v.price).filter((p) => typeof p === 'number');
    if (prices.length > 0) {
      this.basePriceStored = Math.min(...prices);
    }
  }
  next();
});

/**
 * Export the Product Mongoose Model.
 * If model is already registered (useful in watch/hot-reload environments), reuse it.
 */
const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

export default Product;
